name: CI

on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request:

jobs:
  ci:
    uses: huanshankeji/.github/.github/workflows/gradle-ci.yml@v0.5.2
    secrets: inherit
    with:
      jdk-versions: 17-temurin
      runs-on: ubuntu-latest
