name: Publish

on:
  workflow_dispatch:
  push:
    branches: ["**"]

jobs:
  publish:
    uses: huanshankeji/.github/.github/workflows/gradle-maven-publish.yml@improve-cross-repo-dependency
    secrets: inherit
    with:
      jdk-versions: 17-temurin
      runs-on: ubuntu-latest
