name: Publish

on:
  workflow_dispatch:
  push:
    branches: ["**"]

jobs:
  publish:
    uses: huanshankeji/.github/.github/workflows/open-source-convention-gradle-maven-publish.yml@v0.4.1
    secrets: inherit
    with:
      jdk-versions: 17-temurin
      runs-on: ubuntu-latest
